[package]
name = "wyz_aoc_2023_d01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wyz_aoc = { path = "../../../../rust" }
nom = "7"
